#!/bin/bash -xv
set -e

pre_test_cleanup() {
  rm -rf venv data venv_test
}

pre_test_setup() {
  rm -rf venv data venv_test
  virtualenv -p python2.7 venv_test
  venv_test/bin/pip install -r etc/requirements-test.txt
}

use_fake_nntp_creds() {
  echo "Using fake nntp creds"
  sed -ri "s/changeme_nntp_username//g" data/config.php
  sed -ri "s/changeme_nntp_password//g" data/config.php
  sed -ri "s/changeme_nntp_server/freenews.netfront.net/g" data/config.php
  sed -ri "s/changeme_nntp_port/119/g" data/config.php
  head data/config.php
}

step1_cli_setup() {
  bin/build_virtualenv
  bin/build_nzedb
  bin/setup_data_dir
  use_fake_nntp_creds
  bin/start_nzedb
}

step1_test() {
  # nzedb is up
  venv_test/bin/http --session test --check-status :8800/install/
  
  # adminer is up - needs to be poked twice to pass
  # TODO: Figure out why it always fails on the first poke
  # venv_test/bin/http :8880/
  # venv_test/bin/http --check-status :8880/
}

step2_web_setup() {
  venv_test/bin/http --session test --check-status :8800/install/step1.php | \
    grep "No problems were found and you are ready to install"

  venv_test/bin/http --session test --check-status :8800/install/step2.php | \
    grep "Database Setup"

  venv_test/bin/http \
    --session=test \
    --check-status \
    --follow \
    --form \
    --all :8800/install/step2.php \
      db_system=mysql \
      host=database \
      sql_port=3306 \
      sql_socket="" \
      user=nzedb \
      pass=nzedb \
      db=nzedb
}

step3_sane_defaults() {
  echo "TODO: sane defaults"
}

step4_verification() {
  echo "TODO: verification"
}

post_test_cleanup() {
  bin/stop_nzedb
}

# Main
pre_test_setup

step1_cli_setup
step1_test

step2_web_setup

step3_sane_defaults

step4_verification

post_test_cleanup

