version: '2'
services:

  database:
    extends:
      file: common.yml
      service: database
    build: mariadb

  nzedb:
    extends:
      file: common.yml
      service: nzedb
    build: nzedb
    links:
      - database
      - redis
    depends_on:
      - database
      - redis

  adminer:
    extends:
      file: common.yml
      service: adminer
    links: 
      - database:db
    depends_on:
      - database

  redis:
    extends:
      file: common.yml
      service: redis
