version: '2'
services:

  database:
    extends:
      file: common.yml
      service: database
    build: mariadb

  nzedb:
    extends:
      file: common.yml
      service: nzedb
    build: nzedb
    links:
      - database
    depends_on:
      - database

  adminer:
    extends:
      file: common.yml
      service: adminer
    links: 
      - database:db
    depends_on:
      - database
